require('dotenv').config()
const express = require('express')
const app = express()
const port = process.env.PORT;
const cors = require('cors')
const connectDb = require('./config/db')
const authRoutes = require('./routes/authRoutes')
const userRoutes = require('./routes/userRoutes')
const visitorRoutes = require('./routes/visitorRoutes')
const appointmentRoutes = require('./routes/appointmentRoutes')
const checkLogRoutes = require('./routes/checkLogRoutes')
const passRoutes = require('./routes/passRoutes')

connectDb()
app.use(express.json({ limit: '10mb' }))
app.use(cors())
app.use('/api/auth', authRoutes)
app.use('/api/users',userRoutes)
app.use('/api/visitors' , visitorRoutes)
app.use('/api/appointments',appointmentRoutes)
app.use('/api/checklogs',checkLogRoutes)
app.use('/api/passes' , passRoutes)
app.listen(port,()=>{
    console.log(`server is running on http://localhost:${port}`)
})
